server:
  port: 8080
  servlet:
    context-path: /iam

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
