server:
  port: 8080
  servlet:
    context-path: /iam

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "H70wBs8w6tYCEItpxkMMcuZ924MoFhkv6sqPk9nnRybuwCo4SOI0vaE/3bzkBZ4e"
  valid-duration: 3600
  refreshable-duration: 36000
